name: "Challenge 03"
description: ""

inputs:
  command:
    description: "Make task to execute"
    required: true
  go-version:
    description: "Go version to be used in the checks"
    required: false
    default: "1.21.0"

runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - uses: gcjuarez/crashcourse-githubactions-playground/test@v3
      if: inputs.command == 'test'
      with:
        # modules: ${{ inputs.modules }}
        go-version: ${{ inputs.go-version }}
        # tools-dir: ${{ inputs.tools-dir }}

    - uses: gcjuarez/crashcourse-githubactions-playground/lint@v3
      if: inputs.command == 'lint'
      with:
        # modules: ${{ inputs.modules }}
        go-version: ${{ inputs.go-version }}
        # tools-dir: ${{ inputs.tools-dir }}

