name: "Install go binary tool"
description: ""

inputs:
  go-version:
    description: "Go version to set up"
    default: "1.20.5"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        cache: false