name: Run a composite action
on: [push]

# Add the necesary params on the question marks to make the workflow work
jobs:
  hello_world_composite:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - run: ls -a ./.github/actions/
        shell: bash
      - id: foo
        uses: gcjuarez/crashcourse-githubactions-playground@v2
        with:
          who-to-greet: 'Gera'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
